Update purge_tryhackme.yml

diff --git a/.github/workflows/purge_tryhackme.yml b/.github/workflows/purge_tryhackme.yml
--- a/.github/workflows/purge_tryhackme.yml
+++ b/.github/workflows/purge_tryhackme.yml
@@ -1,4 +1,4 @@
-name: Purge Cache and Check Response
+name: Update Tryhackme
 
 on:
   schedule:
@@ -10,12 +10,16 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Install jq
-      run: sudo apt-get update && sudo apt-get install -y jq
-
     - name: Perform PURGE Request and Check Response
       id: purge
       run: |
-        RESPONSE=$(curl -s -X PURGE "https://camo.githubusercontent.com/f7fc0668b22817d7f64fc1d54f3d835f2ac057df486f2fc696e00a05a828bcc1/68747470733a2f2f7472796861636b6d652d6261646765732e73332e616d617a6f6e6177732e636f6d2f7366622e706e673f636163686562757374696e673d74727565")
+        RESPONSE=$(curl -s -X PURGE "https://camo.githubusercontent.com/your_url_here")
         echo "Response Body: $RESPONSE"
-      
+        
+        # Adjusted grep pattern to account for whitespace
+        if echo "$RESPONSE" | grep -E -q '"status"[[:space:]]*:[[:space:]]*"ok"'; then
+          echo "Purge successful!"
+        else
+          echo "Error: Response did not contain 'status: ok'"
+          exit 1
+        fi
